let s1 = { name: "Aman", age: 15, fatherName: "Ramesh", motherName: "Sita" };
let s2 = { name: "Riya", age: 16, fatherName: "Sanjay", motherName: "Geeta" };
let s3 = { name: "Anu", age: 55, fatherName: "Mahesh", motherName: "Lata" };
let s4 = { name: "Rubi", age: 27, fatherName: "Raj", motherName: "Meena" };
let s5 = { name: "Ronak", age: 37, fatherName: "Amit", motherName: "Sunita" };

console.log(s1, s2, s3, s4, s5);
